import { HomePageData } from "@/types";

export const homePageData: HomePageData = {
  hero: {
    eyebrow: "01 / Artist Statement & Portfolio",
    headline: "Observing quiet human moments, domestic rest, and cultural transition between Kerala and Britain.",
    statement: "Amritha Jalaja Devi is a visual artist originally from Mavelikara in Alappuzha, Kerala, currently based in the United Kingdom. Her practice is primarily figurative, observing everyday domestic environments—sleeping, resting, and quiet human connections that explore wellbeing, vulnerability, memory, and belonging.",
    primaryCta: { label: "View Selected Work", href: "/work" },
    secondaryCta: { label: "Download CV", href: "/cv" },
    featuredArtwork: {
      title: "Shared Silence",
      year: "2024",
      medium: "Oil on Canvas",
      dimensions: "150 × 120 cm",
      location: "British Council Study UK Exhibition, New Delhi",
      image: "/artworks/work/work20.jpg",
    },
  },
  highlightBanner: {
    eyebrow: "02 / Key Recognition & Selection",
    title: "Selected for British Council Study UK Creative Connections 2026",
    badge: "British Council Featured Artist",
    description: "Amritha's painting 'Shared Silence' (2024) was selected by the British Council for the Study UK Creative Connections 2026 exhibition in New Delhi. The British Council also featured her artwork and profile as part of their international cultural programme connecting Britain and India.",
    cta: { label: "Explore Recognition & Profile", href: "/recognition" },
    metrics: [
      { value: "2026", label: "British Council Selection" },
      { value: "MA", label: "De Montfort University, UK", highlight: true },
      { value: "BFA", label: "Fine Arts Mavelikara, Kerala" },
      { value: "2022", label: "Kochi Biennale Public Project", highlight: true },
    ],
  },
  keyProjects: [
    {
      id: "shared-silence",
      title: "Shared Silence",
      subtitle: "British Council Selection (New Delhi 2026)",
      year: "2024",
      medium: "Oil on Canvas",
      location: "British Council Study UK Creative Connections Exhibition, New Delhi",
      image: "/artworks/work/work1.jpg",
      aspectRatio: "aspect-[4/3]",
      description: "Selected for the British Council Study UK Creative Connections 2026 exhibition in New Delhi. The painting explores quietness, rest, emotional connection, and unspoken human experience.",
      tags: ["British Council", "Figurative Painting", "Oil on Canvas"],
    },
    {
      id: "varavazhikal-mural",
      title: "Varavazhikal Public Mural Project",
      subtitle: "Kochi Biennale Foundation Collaboration",
      year: "2022",
      medium: "Public Mural & Mineral Pigments",
      location: "Alappuzha, Kerala, India",
      image: "/artworks/mural-01.jpg",
      aspectRatio: "aspect-[4/3]",
      description: "A collaborative public mural project in Alappuzha associated with the Kochi Biennale Foundation, exploring how art becomes part of a public space and interacts directly with local residents.",
      tags: ["Public Mural", "Kochi Biennale", "Community Art"],
    },
    {
      id: "leicester-cultural-mural",
      title: "Kerala Visual Heritage Murals",
      subtitle: "UK Commercial & Civic Commission",
      year: "2024",
      medium: "Large-Scale Architectural Mural",
      location: "90's Mix Resto Bar, Leicester, UK",
      image: "/artworks/mural-02.jpg",
      aspectRatio: "aspect-[4/3]",
      description: "A major UK commission creating large-scale murals drawing from Kerala's cultural memory, visual heritage, traditional street celebrations, and everyday life within a British city context.",
      tags: ["UK Commission", "Architectural Mural", "Cultural Heritage"],
    },
    {
      id: "rest-and-quietude",
      title: "Rest, Sleep & Domestic Space Series",
      subtitle: "MA Contemporary Arts Practice Showcase",
      year: "2024–2025",
      medium: "Oil & Acrylic on Canvas",
      location: "De Montfort University, Leicester, UK",
      image: "/artworks/work/work2.jpg",
      aspectRatio: "aspect-[4/3]",
      description: "A major series exploring sleep and rest as central subjects—examining how ordinary domestic moments reflect wellbeing, vulnerability, memory, and migration.",
      tags: ["Figurative Series", "MA Practice", "Domestic Space"],
    },
  ],
  pressFeatures: [
    {
      publication: "British Council Study UK Programme",
      date: "2024–2026",
      title: "“British Council Selects Amritha Jalaja Devi's 'Shared Silence' for New Delhi Showcase”",
      excerpt: "Highlighting creative connections between India and the UK, featuring Devi's figurative painting exploring quietness, rest, and unspoken emotional bonds.",
      linkText: "Read British Council Profile",
      url: "/recognition",
    },
    {
      publication: "Kochi Biennale Foundation Archive",
      date: "2022",
      title: "“Varavazhikal Public Mural Project: Bringing Fine Art into Everyday Public Spaces in Alappuzha”",
      excerpt: "Exploring community engagement and collaborative public art in Kerala, demonstrating how visual art interacts directly with local residents outside gallery walls.",
      linkText: "View Mural Documentation",
      url: "/public-art",
    },
  ],
};
