import { HomePageData } from "@/types";

export const homePageData: HomePageData = {
  hero: {
    eyebrow: "01 / Artist Statement & Portfolio",
    headline: "Exploring tactile memory, monumental bronze sculpture, and site-responsive public art.",
    statement: "Amritha Jalaja Devi is an acclaimed contemporary visual artist and sculptor whose practice bridges raw metallic form, glazed ceramics, and architectural canvas installations. Based in the UK, her work examines environmental resilience, cultural lineage, and spatial transformation.",
    primaryCta: { label: "View Selected Work", href: "/work" },
    secondaryCta: { label: "Download CV", href: "/cv-dummy.pdf" },
    featuredArtwork: {
      title: "Ethereal Forms No. 4",
      year: "2025",
      medium: "Bronze & Glazed Terracotta",
      dimensions: "180 × 95 × 80 cm",
      location: "Contemporary Sculpture Gallery, London",
      image: "/artworks/work/work20.jpg?auto=format&fit=crop&w=1200&q=80",
    },
  },
  highlightBanner: {
    eyebrow: "02 / Key Accreditation & Recognition",
    title: "British Council Visual Arts Fellow & International Grant Recipient",
    badge: "UK Global Talent Portfolio",
    description: "Recognized by the British Council for exceptional contribution to UK-India cultural exchange and public art sculpture. Recipient of major international production grants supporting site-specific installations at the Yorkshire Sculpture Park and Venice Biennale Collateral Exhibitions.",
    cta: { label: "Explore Awards & GTV Evidence", href: "/recognition" },
    metrics: [
      { value: "12+", label: "International Shows" },
      { value: "2", label: "UK Civic Monuments", highlight: true },
      { value: "2025", label: "V&A Museum Showcase" },
      { value: "100%", label: "Original Studio Work", highlight: true },
    ],
  },
  keyProjects: [
    {
      id: "echoes-of-silence",
      title: "Echoes of Silence",
      subtitle: "UK Public Art Commission",
      year: "2024–2025",
      medium: "Cast Bronze & Weathering Steel",
      location: "Yorkshire Sculpture Park & London Civic Plaza",
      image: "/artworks/work/work15.jpg??auto=format&fit=crop&w=1200&q=80",
      aspectRatio: "aspect-[4/3]",
      description: "A monumental 4-meter bronze sculpture commissioned for a prominent UK civic square, investigating urban memory and industrial heritage.",
      tags: ["Public Sculpture", "UK Commission", "Bronze"],
    },
    {
      id: "terra-incognita",
      title: "Terra Incognita",
      subtitle: "Biennale Solo Pavilion",
      year: "2024",
      medium: "Glazed Terracotta & Earth Pigments",
      location: "Venice Biennale Collateral Exhibition",
      image: "/artworks/work/work16.jpg??auto=format&fit=crop&w=1200&q=80",
      aspectRatio: "aspect-[4/3]",
      description: "A suite of 14 sculptural ceramic vessels exploring sea-level vulnerability, ancient trade route relics, and ecological memory.",
      tags: ["Solo Pavilion", "Ceramics", "Biennale"],
    },
    {
      id: "lumina-vessel-of-light",
      title: "Lumina: Vessel of Light",
      subtitle: "Museum Canvas Installation",
      year: "2025",
      medium: "Oil on Raw Flax & Bronze Assemblage",
      location: "Victoria & Albert Museum (V&A), London",
      image: "/artworks/work/work17.jpg??auto=format&fit=crop&w=1200&q=80",
      aspectRatio: "aspect-[4/3]",
      description: "An architectural multi-panel canvas installation examining light diffusion, tactile surface pigment, and spatial stillness.",
      tags: ["Museum Show", "Oil Painting", "Spatial Art"],
    },
  ],
  pressFeatures: [
    {
      publication: "The Guardian Fine Art Review",
      date: "October 2025",
      title: "“Amritha Jalaja Devi's Sculptural Language Redefines Contemporary Space”",
      excerpt: "Devi commands raw bronze and clay with rare poetic sensitivity, establishing her as one of the most compelling voices in British contemporary sculpture.",
      linkText: "Read Full Guardian Review",
      url: "/press",
    },
    {
      publication: "Art UK Magazine",
      date: "June 2025",
      title: "“Top 10 Contemporary Sculptors Shaping Public Landscapes in Britain”",
      excerpt: "Her site-responsive installations bridge historical narrative with modern materiality, creating lasting civic landmarks across the United Kingdom.",
      linkText: "Read Art UK Feature",
      url: "/press",
    },
  ],
};
