import { PressArticle } from "@/types";

export const pressData: PressArticle[] = [
  {
    id: "guardian-cultural-feature-2025",
    articleTitle: "Amritha Jalaja Devi: Sculpting Industrial Landscapes & Ecological Time",
    publicationName: "The Guardian (Cultural Supplement)",
    date: "October 14, 2025",
    category: "Feature",
    author: "Adrian Searle",
    excerpt: "An in-depth critical feature on Amritha Jalaja Devi's monumental Yorkshire Sculpture Park bronze commission and her pioneering research into mineral patinas.",
    coverImage: "https://images.unsplash.com/photo-1544717305-2782549b5136?q=80&w=1200&auto=format&fit=crop",
    externalLink: "https://theguardian.com/artanddesign",
  },
  {
    id: "art-uk-civic-monuments-2025",
    articleTitle: "UK Civic Commissions Spotlight: Bronze Forms in Public Plazas",
    publicationName: "Art UK Magazine",
    date: "August 28, 2025",
    category: "Exhibition Coverage",
    author: "Dr. Rachel Higgins",
    excerpt: "Examining the social impact and architectural integration of Amritha Jalaja Devi's permanent public art monuments in Northern England.",
    coverImage: "https://images.unsplash.com/photo-1579783901460-e4d6c62bb9e3?q=80&w=1200&auto=format&fit=crop",
    externalLink: "https://artuk.org/discover/stories",
  },
  {
    id: "art-monthly-venice-biennale-2024",
    articleTitle: "60th Venice Biennale Collateral: Terra Incognita Review",
    publicationName: "Art Monthly UK",
    date: "May 2024 Issue (No. 476)",
    category: "Review",
    author: "Patricia Bickers",
    excerpt: "A compelling review of the solo collateral pavilion at Palazzo Mora, highlighting the interplay between terracotta sea vessels and ecological vulnerability.",
    coverImage: "https://images.unsplash.com/photo-1561214115-f2f134cc4912?q=80&w=1200&auto=format&fit=crop",
    externalLink: "https://artmonthly.co.uk",
  },
  {
    id: "sculpture-magazine-interview-2024",
    articleTitle: "Biomorphic Forms & Mineral Patinas: Conversation with Amritha Jalaja Devi",
    publicationName: "International Sculpture Magazine",
    date: "November / December 2024",
    category: "Interview",
    author: "Glenn Harper",
    excerpt: "An extended studio interview discussing foundry processes, raw sienna pigments, and large-scale public casting techniques.",
    coverImage: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=1200&auto=format&fit=crop",
    externalLink: "https://sculpture.org",
  },
  {
    id: "times-top-10-artists-2025",
    articleTitle: "Top 10 Contemporary Sculptors Shaping British Art in 2025",
    publicationName: "The Times (Saturday Review)",
    date: "January 18, 2025",
    category: "Feature",
    author: "Waldemar Januszczak",
    excerpt: "Selected as one of the UK's most promising contemporary sculptors for exceptional contributions to civic space and environmental art.",
    coverImage: "/images/hero-artwork.jpg",
    externalLink: "https://thetimes.co.uk/culture",
  },
  {
    id: "bbc-culture-urban-regeneration",
    articleTitle: "Public Monuments & Urban Regeneration in Northern England",
    publicationName: "BBC Culture & Arts",
    date: "February 4, 2025",
    category: "Exhibition Coverage",
    author: "Mark Lawson",
    excerpt: "A BBC documentary feature investigating how contemporary public bronze sculptures foster community identity in Manchester and London.",
    coverImage: "https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?q=80&w=1200&auto=format&fit=crop",
    externalLink: "https://bbc.com/culture",
  },
];
