import { PublicArtProject } from "@/types";

export const publicArtData: PublicArtProject[] = [
  {
    id: "civic-horizon-manchester",
    title: "Civic Horizon Monumental Sculpture",
    medium: "Forged Weathering Steel, Cast Bronze & Glazed Ceramic Reliefs",
    location: "Civic Plaza & St. Peter's Square",
    city: "Manchester",
    country: "United Kingdom",
    year: "2024–2025",
    commissioningBody: "Manchester City Council & UK Heritage Arts Trust",
    dimensions: "520 × 240 × 180 cm",
    impactMetric: "Permanent Civic Installation — Estimated 450,000+ Annual Public Audience",
    description: "A monumental 5.2-meter permanent civic public art installation commemorating post-industrial labor transformation in Northern England. Combining heavy weathering steel with bronze mineral patinas.",
    coverImage: "/artworks/mural-01.jpg?q=80&w=1200&auto=format&fit=crop",
    externalLink: "https://manchester.gov.uk/arts",
  },
  {
    id: "docklands-eco-mural-london",
    title: "River & Relief: Thames Estuary Ecological Mural",
    medium: "Architectural Ceramic Relief, Mineral Pigments & Bronze Inlays",
    location: "East London Docklands Regeneration Site & Light Rail Promenade",
    city: "London",
    country: "United Kingdom",
    year: "2024",
    commissioningBody: "London Docklands Development Corporation & Arts Council England",
    dimensions: "28 × 4.5 meters (126 sq meters)",
    impactMetric: "Permanent Public Frieze — Commissioned for Urban Regeneration",
    description: "A 28-meter architectural ceramic mural and low-relief sculpture installation examining maritime tidal history and Thames Estuary ecosystem preservation.",
    coverImage: "/artworks/mural-02.jpg?q=80&w=1200&auto=format&fit=crop",
    externalLink: "https://artscouncil.org.uk",
  },
  {
    id: "sanctuary-botanical-sculpture",
    title: "Sanctuary of Soil & Terracotta",
    medium: "High-Fired Terracotta Vessels & Raw Sienna Bronze Elements",
    location: "Royal Botanic Garden Sculpture Courtyard",
    city: "Edinburgh",
    country: "Scotland, UK",
    year: "2023–2024",
    commissioningBody: "Scottish National Heritage & Royal Botanic Garden Trust",
    dimensions: "340 × 190 × 160 cm",
    impactMetric: "Public Botanical Garden Sculpture Feature",
    description: "A site-specific outdoor pavilion installation of interconnected ceramic vessels investigating soil biodiversity, seed memory, and geological time.",
    coverImage: "/artworks/mural-03.jpg?q=80&w=1200&auto=format&fit=crop",
    externalLink: "https://rbge.org.uk",
  },
];
