import { PublicArtProject } from "@/types";

export const publicArtData: PublicArtProject[] = [
  {
    id: "varavazhikal-mural-alappuzha",
    title: "Varavazhikal Public Mural Project",
    medium: "Public Mural & Mineral Pigments",
    location: "Alappuzha Promenade",
    city: "Alappuzha, Kerala",
    country: "India",
    year: "2022",
    commissioningBody: "Kochi Biennale Foundation Collaboration",
    dimensions: "18 × 3.5 meters",
    impactMetric: "Public Community Mural — Interacting Directly with Local Residents",
    description: "Participated in the collaborative public mural project Varavazhikal in Alappuzha in 2022, associated with the Kochi Biennale Foundation. Working on a public-facing project gave me a different understanding of art—seeing how art becomes part of a place and interacts directly with people.",
    coverImage: "/artworks/mural-01.jpg",
    externalLink: "https://kochibiennale.org",
  },
  {
    id: "leicester-resto-mural",
    title: "Kerala Heritage Architectural Murals",
    medium: "Large-Scale Acrylic & Pigment Mural",
    location: "90’s Mix Resto Bar Promenade",
    city: "Leicester",
    country: "United Kingdom",
    year: "2024",
    commissioningBody: "90's Mix Public & Commercial Commission",
    dimensions: "12 × 3 meters",
    impactMetric: "Cultural Heritage Feature — Connecting Kerala & British Urban Life",
    description: "A major UK commission creating large-scale murals drawing from Kerala’s cultural memory and visual heritage, including imagery inspired by familiar Kerala street life and traditional celebrations within a British city context.",
    coverImage: "/artworks/mural-02.jpg",
    externalLink: "https://instagram.com",
  },
  {
    id: "shared-silence-public-showcase",
    title: "Shared Silence — British Council Selection",
    medium: "Oil on Canvas & Featured Installation",
    location: "British Council Study UK Exhibition",
    city: "New Delhi",
    country: "India",
    year: "2024–2026",
    commissioningBody: "British Council International Programme",
    dimensions: "150 × 120 cm",
    impactMetric: "British Council International Selection & Featured Profile",
    description: "Selected by the British Council for the Study UK Creative Connections 2026 exhibition in New Delhi. The painting explores quietness, rest, emotional connection, and unspoken human bonds.",
    coverImage: "/artworks/mural-03.jpg",
    externalLink: "https://britishcouncil.org",
  },
  {
    id: "varavazhikal-mural-alappuzha4",
    title: "Varavazhikal Public Mural Project",
    medium: "Public Mural & Mineral Pigments",
    location: "Alappuzha Promenade",
    city: "Alappuzha, Kerala",
    country: "India",
    year: "2022",
    commissioningBody: "Kochi Biennale Foundation Collaboration",
    dimensions: "18 × 3.5 meters",
    impactMetric: "Public Community Mural — Interacting Directly with Local Residents",
    description: "Participated in the collaborative public mural project Varavazhikal in Alappuzha in 2022, associated with the Kochi Biennale Foundation. Working on a public-facing project gave me a different understanding of art—seeing how art becomes part of a place and interacts directly with people.",
    coverImage: "/artworks/mural-04.jpg",
    galleryImages:[
        "/artworks/1.jpg",
        "/artworks/2.jpg",
        "/artworks/3.jpg"
    ],
    externalLink: "https://kochibiennale.org",
  },
];
