import { RecognitionItem } from "@/types";

export const recognitionData: RecognitionItem[] = [
  {
    id: "british-council-creative-connections-2026",
    awardTitle: "British Council Study UK Creative Connections Selection",
    awardingBody: "British Council International Programme",
    year: "2024–2026",
    status: "Selected",
    category: "International Exhibition Selection",
    location: "New Delhi & London",
    description: "Painting 'Shared Silence' (2024) selected for the British Council Study UK Creative Connections 2026 exhibition in New Delhi. The British Council also featured her artwork and artist profile as part of their international cultural programme connecting Britain and India.",
    link: "https://britishcouncil.org",
  },
  {
    id: "kochi-biennale-varavazhikal-2022",
    awardTitle: "Varavazhikal Collaborative Public Mural Project",
    awardingBody: "Kochi Biennale Foundation",
    year: "2022",
    status: "Selected",
    category: "Public Art & Community Mural",
    location: "Alappuzha, Kerala, India",
    description: "Selected to participate in the collaborative public mural project Varavazhikal in Alappuzha, exploring public engagement and visual art outside gallery walls.",
    link: "https://kochibiennale.org",
  },
  {
    id: "de-montfort-ma-showcase-2024",
    awardTitle: "MA Contemporary Arts Practice Showcase Selection",
    awardingBody: "De Montfort University",
    year: "2024",
    status: "Featured",
    category: "Academic & Fine Art Recognition",
    location: "Leicester, United Kingdom",
    description: "Recognized for outstanding postgraduate studio practice connecting quiet human domestic moments with cultural transition between Kerala and Britain.",
    link: "https://dmu.ac.uk",
  },
  {
    id: "raja-ravi-varma-bfa-distinction-2019",
    awardTitle: "BFA Fine Arts Academic Recognition in Painting",
    awardingBody: "Raja Ravi Varma College of Fine Arts",
    year: "2019",
    status: "Won",
    category: "Degree Distinction",
    location: "Mavelikara, Kerala, India",
    description: "Graduated with First Class Honors in BFA Painting, specializing in figurative oil painting, drawing, and ordinary human experience on canvas.",
    link: "https://mavelikara.ac.in",
  },
];
