import { RecognitionItem } from "@/types";

export const recognitionData: RecognitionItem[] = [
  {
    id: "british-council-fellowship-2025",
    awardTitle: "British Council Visual Arts Fellowship",
    awardingBody: "British Council & UK Visual Arts Directorate",
    year: "2025",
    status: "Offered",
    category: "International Research Fellowship",
    location: "London & Venice",
    description: "Prestigious UK fellowship awarded to exceptional visual artists conducting material research into ecological ceramics and public bronze casting.",
    link: "https://visualarts.britishcouncil.org",
  },
  {
    id: "uk-heritage-public-art-award-2025",
    awardTitle: "UK National Heritage Public Art Award",
    awardingBody: "Royal Society of British Sculptors & Heritage Trust",
    year: "2025",
    status: "Won",
    category: "Public Sculpture Commission",
    location: "Manchester, UK",
    description: "First Place award for the monumental 'Civic Horizon' public sculpture installation in Manchester Civic Plaza.",
    link: "https://rbs.org.uk/awards",
  },
  {
    id: "venice-biennale-ecc-award-2024",
    awardTitle: "ECC Personal Structures International Art Award",
    awardingBody: "European Cultural Centre (ECC) Venice",
    year: "2024",
    status: "Nominated",
    category: "Contemporary Sculpture",
    location: "Venice, Italy",
    description: "Nominated for outstanding solo pavilion installation ('Terra Incognita') at the 60th Venice Biennale Collateral Event.",
    link: "https://ecc-italy.eu",
  },
  {
    id: "swiss-art-foundation-residency-2024",
    awardTitle: "Swiss International Sculpture Residency & Fellowship",
    awardingBody: "Swiss Art Foundation & Kunsthalle Basel",
    year: "2024",
    status: "Selected",
    category: "International Residency",
    location: "Basel, Switzerland",
    description: "Selected as one of 4 international sculptors for an intensive 3-month studio research residency in heavy metallurgy and bronze casting.",
    link: "https://kunsthallebasel.ch",
  },
  {
    id: "henry-moore-sculpture-grant-2024",
    awardTitle: "Henry Moore Foundation Sculpture Production Grant",
    awardingBody: "Henry Moore Foundation",
    year: "2024",
    status: "Shortlisted",
    category: "Production Grant",
    location: "Leeds & Perry Green, UK",
    description: "Shortlisted for major production funding supporting large-scale public bronze and terracotta assemblages.",
    link: "https://henry-moore.org",
  },
  {
    id: "royal-academy-summer-exhibition-2023",
    awardTitle: "Royal Academy Summer Exhibition Feature Selection",
    awardingBody: "Royal Academy of Arts",
    year: "2023",
    status: "Selected",
    category: "Museum Exhibition Feature",
    location: "London, UK",
    description: "Selected by the Royal Academy Selection Committee for prominent display in the RA Main Galleries.",
    link: "https://royalacademy.org.uk",
  },
  {
    id: "jerwood-fine-art-prize-2023",
    awardTitle: "Jerwood Contemporary Fine Art Prize",
    awardingBody: "Jerwood Arts & Foundation",
    year: "2023",
    status: "Shortlisted",
    category: "National Art Prize",
    location: "London, UK",
    description: "Shortlisted among national UK early-to-mid career contemporary artists for outstanding sculptural practice.",
    link: "https://jerwoodarts.org",
  },
];
