import { Artwork, CategoryFilterOption, CategorySlug, StudioWorkItem } from "@/types";

export const categoryOptions: CategoryFilterOption[] = [
  { id: "all", label: "All Curated Works", count: 8 },
  { id: "series", label: "Major Series", count: 4 },
  { id: "recent", label: "Recent Works (2025)", count: 3 },
  { id: "commissions", label: "Commissioned Works", count: 3 },
  { id: "public-art", label: "Public Art & Monuments", count: 2 },
  { id: "studio", label: "Studio Setup & In-Progress Works", count: 6 },
];

export function normalizeCategorySlug(param?: string): CategorySlug {
  if (!param) return "all";
  const slug = param.toLowerCase().trim();
  if (slug === "studio" || slug === "in-progress" || slug === "studio-setup") return "studio";
  if (slug === "commissions" || slug === "uk-commissions") return "commissions";
  if (slug === "series" || slug === "paintings" || slug === "biennale" || slug === "paintings-sculptures") return "series";
  if (slug === "recent" || slug === "recent-works") return "recent";
  if (slug === "public-art" || slug === "public") return "public-art";
  return "all";
}

export const artworksData: Artwork[] = [
  {
    id: "ethereal-forms-no-4",
    title: "Ethereal Forms No. 4",
    category: "series",
    categoryLabel: "Major Series",
    medium: "Cast Bronze & Glazed Terracotta",
    year: "2025",
    dimensions: "180 × 95 × 80 cm",
    location: "Contemporary Sculpture Gallery, London",
    image: "/images/hero-artwork.jpg",
    aspectRatio: "landscape",
    description: "A monumental sculpture investigating fluid organic geometry and mineral patina interaction.",
    featured: true,
  },
  {
    id: "echoes-of-silence-monument",
    title: "Echoes of Silence",
    category: "commissions",
    categoryLabel: "Commissioned Works",
    medium: "Cast Bronze & Weathering Steel",
    year: "2025",
    dimensions: "400 × 210 × 180 cm",
    location: "Yorkshire Sculpture Park & London Civic Plaza",
    image: "https://images.unsplash.com/photo-1544717305-2782549b5136?q=80&w=1200&auto=format&fit=crop",
    aspectRatio: "landscape",
    description: "UK Public Art Commission exploring industrial transformation through raw bronze forms.",
    featured: true,
  },
  {
    id: "monolith-in-sienna",
    title: "Monolith in Sienna",
    category: "recent",
    categoryLabel: "Recent Works",
    medium: "Raw Bronze & Raw Sienna Pigment",
    year: "2025",
    dimensions: "140 × 65 × 50 cm",
    location: "Studio Collection, Edinburgh",
    image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=1200&auto=format&fit=crop",
    aspectRatio: "portrait",
    description: "A vertical monolithic bronze study examining mineral corrosion and earth pigment application.",
    featured: true,
  },
  {
    id: "terra-incognita-vessel-8",
    title: "Terra Incognita Vessel No. 8",
    category: "series",
    categoryLabel: "Major Series",
    medium: "Glazed Terracotta & Earth Oxides",
    year: "2024",
    dimensions: "95 × 60 × 60 cm",
    location: "Venice Biennale Collateral Pavilion",
    image: "https://images.unsplash.com/photo-1561214115-f2f134cc4912?q=80&w=1200&auto=format&fit=crop",
    aspectRatio: "square",
    description: "Sculptural ceramic vessel addressing maritime trade relics and sea-level rise.",
  },
  {
    id: "lumina-vessel-of-light",
    title: "Lumina: Vessel of Light",
    category: "recent",
    categoryLabel: "Recent Works",
    medium: "Oil on Raw Flax & Bronze Assemblage",
    year: "2025",
    dimensions: "210 × 160 cm",
    location: "Victoria & Albert Museum (V&A), London",
    image: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=1200&auto=format&fit=crop",
    aspectRatio: "portrait",
    description: "Multi-panel architectural painting exploring light diffusion across textured raw flax.",
  },
  {
    id: "ancestral-topography",
    title: "Ancestral Topography No. 2",
    category: "series",
    categoryLabel: "Major Series",
    medium: "Raw Bronze & Oxidized Copper",
    year: "2024",
    dimensions: "165 × 80 × 75 cm",
    location: "Private Collection, Zurich",
    image: "https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?q=80&w=1200&auto=format&fit=crop",
    aspectRatio: "landscape",
    description: "Biomorphic bronze installation exploring geographical memory and ancestral lineage.",
  },
  {
    id: "civic-horizon-commission",
    title: "Civic Horizon Commission",
    category: "public-art",
    categoryLabel: "Public Art & Monuments",
    medium: "Forged Steel & Cast Bronze",
    year: "2024",
    dimensions: "350 × 180 × 120 cm",
    location: "Civic Art Trust, Manchester",
    image: "https://images.unsplash.com/photo-1579783901460-e4d6c62bb9e3?q=80&w=1200&auto=format&fit=crop",
    aspectRatio: "portrait",
    description: "Large-scale civic sculpture commemorating industrial regeneration in Northern England.",
  },
  {
    id: "submerged-memory-vessel",
    title: "Submerged Memory Vessel",
    category: "series",
    categoryLabel: "Major Series",
    medium: "High-Fired Stoneware & Oxides",
    year: "2024",
    dimensions: "85 × 55 × 55 cm",
    location: "Art Basel Pavilion Showcase",
    image: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?q=80&w=1200&auto=format&fit=crop",
    aspectRatio: "square",
    description: "Textured ceramic vessel with natural oxide glaze exploring marine sediment stratigraphy.",
  },
];

export const studioWorksData: StudioWorkItem[] = [
  {
    id: "studio-setup-1",
    title: "Greenwich Foundry Mold Assembly",
    caption: "Studio, London 2026",
    year: "2026",
    image: "https://images.unsplash.com/photo-1544717305-2782549b5136?q=80&w=1200&auto=format&fit=crop",
    aspectRatio: "portrait",
  },
  {
    id: "studio-setup-2",
    title: "Clay Maquette & Plaster Study",
    caption: "Work in Progress",
    year: "2026",
    image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=1200&auto=format&fit=crop",
    aspectRatio: "square",
  },
  {
    id: "studio-setup-3",
    title: "Patination & Chemical Oxide Testing",
    caption: "Studio, London 2026",
    year: "2026",
    image: "https://images.unsplash.com/photo-1561214115-f2f134cc4912?q=80&w=1200&auto=format&fit=crop",
    aspectRatio: "landscape",
  },
  {
    id: "studio-setup-4",
    title: "Incomplete Charcoal Sketches & Scale Renderings",
    caption: "Work in Progress",
    year: "2026",
    image: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=1200&auto=format&fit=crop",
    aspectRatio: "portrait",
  },
  {
    id: "studio-setup-5",
    title: "Terracotta Clay Prep & Kiln Loading",
    caption: "Studio, London 2025",
    year: "2025",
    image: "https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?q=80&w=1200&auto=format&fit=crop",
    aspectRatio: "square",
  },
  {
    id: "studio-setup-6",
    title: "Lost-Wax Casting & Foundry Workspace",
    caption: "Work in Progress",
    year: "2025",
    image: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?q=80&w=1200&auto=format&fit=crop",
    aspectRatio: "landscape",
  },
];
